Cancel docker pull
NodeFactoryIo/ChainGuardian pull request #320
Opened 2020-11-26 12:52 UTC by morrigan

Closes #301

2020-11-26 16:53 UTC, BeroBurny requested changes
We wanna keep all business logic may as possible in sagas (that mostly reflect on `AddBeaconNode.tsx`)

the simplest soliton (and probably best) can be used in this case is to use the race effect
[https://redux-saga.js.org/docs/api/#raceeffects](https://redux-saga.js.org/docs/api/#raceeffects)
```typescript
export function* pullDockerImage(
    image: string,
): Generator<PutEffect | RaceEffect<CallEffect | TakeEffect>, boolean, [boolean, Action]> {
    yield put(startDockerImagePull());
    const [pull, effect] = yield race([call(BeaconChain.pullImage, image), take(cancelDockerPull)]);
    yield put(endDockerImagePull());

    return effect !== undefined ? false : pull;
}
```
```typescript
export const cancelDockerPull = createAction("network/cancelDockerPull");
```

and this can be simple used in any sagas required to pull an image
**example:**
```typescript
const image = getNetworkConfig(network).dockerConfig.image;
const pullResult = yield call(pullDockerImage, image);
```
**example for cancel:**
```typescript
const onCancelClick = (): void => {
   dispatch(cancelDockerPull());
};
```

2020-11-27 19:41 UTC, morrigan commented
@BeroBurny managed to do it somehow but having issues with Saga types (check @ts-ignore).

Also, we need to have 1 function for starting chain. I think `startLocalBeaconSaga` and `startBeaconChainSaga` should unite :) Not sure if left both by mistake.

2020-11-28 16:55 UTC, BeroBurny requested changes

2020-11-30 08:33 UTC, morrigan commented on src/renderer/ducks/beacon/sagas.ts
> +    const pullSuccess = yield* pullDockerImage(network);
What's the difference?

2020-11-30 09:05 UTC, BeroBurny commented on src/renderer/ducks/beacon/sagas.ts
> +    const pullSuccess = yield* pullDockerImage(network);
differently is handled by saga middleware

https://redux-saga.js.org/docs/basics/UsingSagaHelpers.html
https://redux-saga.js.org/docs/basics/DeclarativeEffects.html

2020-11-30 13:24 UTC, BeroBurny submitted a review, later dismissed
:+1:

2020-11-30 13:59 UTC, BeroBurny approved these changes
:+1:

2020-11-30 13:59 UTC, merged